name: bahirmart
description: A Flutter mobile app for BahirMart
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.4
  carousel_slider: 5.0.0
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.1
  path_provider: ^2.1.5
  sqflite: ^2.3.3
  go_router: ^14.2.8
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/placeholder.png